M48
; DRILL file {KiCad 7.0.2-0} date 2024 May 03, Friday 02:11:53
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-03T02:11:53-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X8.2874Y-5.4331
X8.2874Y-7.2047
X12.4213Y-5.4331
X12.4213Y-7.2047
T0
M30
